version: "3"

services:
  train:
    container_name: scribble-ocr-train
    build:
      context: .
      target: tesseractbuild
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - "./data:/train/tesstrain/data"
    command: sh /app/start.sh
  api:
    container_name: scribble-ocr-api
    build:
      context: .
      target: apitest
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: sh start.sh