version: "3"

services:
  app:
    container_name: scribble-ocr
    build:
      context: .
      dockerfile: Dockerfile_tesseract_training
    ports:
      - 8000:8000
    volumes:
      - ./data:/train/tessdata/data
    command: sh /app/start.sh