
# Run this dockerfile using the command below from repo root
# docker-compose -f docker.dev.yml up -d
# After complete running the build run the command below
# docker exec -ti scribble-ocr bash
# to access the container

# Set docker image
FROM python:3.8-bullseye

# Skip the configuration part
ENV DEBIAN_FRONTEND noninteractive

# Update and install depedencies
RUN apt-get update && \
    apt-get install -y wget unzip bc vim libleptonica-dev git curl 

# Packages to complie Tesseract
RUN apt-get install -y --reinstall make && \
    apt-get install -y g++ autoconf automake libtool pkg-config libpng-dev libjpeg62-turbo-dev libtiff5-dev libicu-dev \
        libpango1.0-dev autoconf-archive

# Set working directory
WORKDIR /app

# Compile Tesseract with training options
RUN cd .. && \
    mkdir train && cd train && \
    wget https://github.com/tesseract-ocr/tesseract/archive/4.1.1.zip && \
	unzip 4.1.1.zip && \
    cd tesseract-4.1.1 && ./autogen.sh && ./configure && make && make install && ldconfig && \
    make training && make training-install && \
    cd ..  && \
    git clone https://github.com/tesseract-ocr/tesstrain.git && \
    cd tesstrain && \
    cd /usr/local/share/tessdata && wget https://github.com/tesseract-ocr/tessdata_best/raw/main/eng.traineddata && \
    wget https://github.com/tesseract-ocr/tessdata_fast/blob/65727574dfcd264acbb0c3e07860e4e9e9b22185/osd.traineddata && \
    mv /usr/local/share/tessdata/ /train

RUN mkdir -p /train/langdata && cd /train/langdata && \
    wget https://raw.githubusercontent.com/tesseract-ocr/langdata_lstm/main/radical-stroke.txt && \
    wget https://raw.githubusercontent.com/tesseract-ocr/langdata_lstm/main/common.punc  && \
    wget https://raw.githubusercontent.com/tesseract-ocr/langdata_lstm/main/font_properties && \
    wget https://raw.githubusercontent.com/tesseract-ocr/langdata_lstm/main/Latin.unicharset  && \
    wget https://raw.githubusercontent.com/tesseract-ocr/langdata_lstm/main/Latin.xheights  && \
    mkdir eng && cd eng && \
    wget https://raw.githubusercontent.com/tesseract-ocr/langdata/main/eng/eng.training_text && \
    wget https://raw.githubusercontent.com/tesseract-ocr/langdata/main/eng/eng.punc && \
    wget https://raw.githubusercontent.com/tesseract-ocr/langdata/main/eng/eng.numbers && \
    wget https://raw.githubusercontent.com/tesseract-ocr/langdata/main/eng/eng.wordlist

RUN mkdir -p /usr/local/share/fonts/journal && \
    wget https://dl.dafont.com/dl/?f=journal -O /tmp/journal.zip && \
    unzip /tmp/journal.zip -d /usr/local/share/fonts/journal

# Setting the TESSDATA_PREFIX prefix
ENV TESSDATA_PREFIX=/train/tessdata


# Installing libraries
RUN python3 -m pip install --upgrade pip
COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY ./tesstrain/Makefile /train/tesstrain/Makefile

# Set the locale
RUN apt-get install -y locales && locale-gen en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8

COPY start.sh /app/start.sh

WORKDIR /train/tesstrain 

