# Source: https://github.com/docker/build-push-action
name: Docker Workflow

on:
  # should trigger on merge to main branch
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          # slight change from the source, adding secret for tag 
          # instead of hard coding the values
          tags: ${{ secrets.DOCKERHUB_TAG }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
