# Source: https://github.com/docker/build-push-action
# Using: Main workflow, custom build context, Docker layer caching with actions/cache@v2
name: Docker Workflow

on:
  # should trigger on merge to main branch
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.0.1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: project
          file: project/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_TAG }}
          # Docker layer cache
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Print image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
