# Name the job
name: Tests

# will only run when code is pushed
on: push

jobs:
  linter:
  # setup environment to run tests
    runs-on: ubuntu-latest
    steps:
    # Checkout the repo.
      - name: Checkout Repo
        uses: actions/checkout@v2.3.4
    
    # Setup Python
      - name: Set up python
        uses: actions/setup-python@v2  
    
    # Use Super Linter, all variables available at https://github.com/github/super-linter
      - name: Use SuperLinter
        uses: github/super-linter@v4
        env:
    # False will only check new/changed files, True will check all files in the repo
    #WARNING!! If set to true will take about 2.5 hours to run.
          VALIDATE_ALL_CODEBASE: false
          # DEFAULT_BRANCH: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}